python train.py \
            --cuda \
            -d coco \
            -v ccdet \
            -bk resnet18 \
            -nk dilated_encoder \
            -fp yolopafpn \
            -hd decoupled_head \
            --ema \
            --fp16 \
            --eval_epoch 10
